version: '3.3'

services:
  server:
    container_name: server
    build:
      context: ./frontend/
    networks:
      - app_network
    volumes:
      - ./frontend/:/var/www/transcendence/:ro
      - ./frontend/server/conf/:/etc/nginx/sites-enabled/:ro
    ports:
      - 443:443
    restart: on-failure
    depends_on:
      - authentication
      - player

  authentication:
    container_name: authentication
    build:
      context: ./backend/services/authentication/
    image: authentication
    env_file:
      - ./backend/dotenv_files/.env
    volumes:
      - ./backend/services/authentication/:/services/authentication/:rw
    networks:
      - app_network
    depends_on:
      - db
    restart: on-failure

  # tournament:
  #   container_name: tournament
  #   build:
  #     context: ./backend/services/tournament/
  #   image: tournament
  #   env_file:
  #     - ./backend/dotenv_files/.env
  #   volumes:
  #     - ./backend/services/tournament/:/services/tournament/:rw
  #   networks:
  #     - app_network
  #   depends_on:
  #     - db
  #   restart: on-failure

  matchmaking:
    container_name: matchmaking
    build:
      context: ./backend/services/matchmaking/
    image: matchmaking
    env_file:
      - ./backend/dotenv_files/.env
    volumes:
      - ./backend/services/matchmaking/:/services/matchmaking/:rw
    networks:
      - app_network
    depends_on:
      - db
    restart: on-failure

  player:
    container_name: player
    build:
      context: ./backend/services/player/
    image: player
    env_file:
      - ./backend/dotenv_files/.env
    volumes:
      - ./backend/services/player/:/services/player/:rw
    networks:
      - app_network
    depends_on:
      - db
    restart: on-failure

  pong:
    container_name: pong
    build:
      context: ./backend/services/pong/
    image: pong
    env_file:
      - ./backend/dotenv_files/.env
    volumes:
      - ./backend/services/pong:/services/pong/:rw
    networks:
      - app_network
    depends_on:
      - db
    restart: on-failure

  db:
    image: postgres:16.2
    container_name: postgres
    restart: unless-stopped
    env_file:
      - ./backend/dotenv_files/.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    env_file:
      - ./backend/dotenv_files/.env
    ports:
      - 8080:80
    networks:
      - app_network
    restart: unless-stopped
    depends_on:
      - db

networks:
  app_network:
    driver: bridge

volumes:
  pgdata:
    driver: local
