services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - '3000:3000'
    networks:
      - app-network
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - '8000:8000'
    volumes:
      - /absolute/path/to/your/project/backend/djangoapp:/app/djangoapp
      - /absolute/path/to/your/project/backend/data/web/static:/data/web/static
      - /absolute/path/to/your/project/backend/data/web/media:/data/web/media
    env_file:
      - ./backend/dotenv_files/.env
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: postgres:16.3-alpine3.20
    container_name: postgres
    env_file:
      - ./backend/dotenv_files/.env
    volumes:
      - /absolute/path/to/your/project/data/postgres/data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
