server {
    listen 443              ssl;
    listen [::]:443         ssl;

    # SSL Configuration
    ssl_protocols           TLSv1.2 TLSv1.3;
    ssl_certificate         /etc/ssl/certs/nginx.crt;
    ssl_certificate_key     /etc/ssl/private/nginx.key;

    root                    /var/www/transcendence;
    index                   index.html;
    server_name             ${DOMAIN_NAME}

    rewrite ^([^.]*[^/])$ $1/ permanent;

    location /favicon.ico { 
        access_log off; 
        log_not_found off; 
    }

    location / {
            try_files $uri $uri/ /index.html;
    }

    location /web/css/ {
        alias /var/www/transcendence/web/css/;
        try_files $uri $uri/ =404;
    }

    location /web/js/ {
        alias /var/www/transcendence/web/js/;
        try_files $uri $uri/ =404;
    }

    location /web/ {
        alias /var/www/transcendence/web/;
        #try_files $uri $uri/ =404;
    }

    location /web/images/ {
        alias /var/www/transcendence/web/images/;
        try_files $uri $uri/ =404;
    }

    location /ws/matchmaking/ {
        proxy_pass http://matchmaking:8000/ws/matchmaking/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    location /ws/pong/ {
        proxy_pass http://pong:8000/ws/pong/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    location /authentication/ {
        proxy_pass http://authentication:8000/authentication/;
    }

    location /authentication/ws/login/ {
        proxy_pass http://authentication:8000/authentication/ws/login/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

	location /player/ {
        proxy_pass http://player:8000/player/;
	}

	location /tournament/ {
        proxy_pass http://tournament:8000/tournament/;
	}

    location /static/ {
        proxy_pass http://player:8000/player/static/;
    }  

    location /media/ {
        proxy_pass http://player:8000/player/media/;
    }

    # Configuração para servir arquivos estáticos com os tipos MIME corretos
     location ~* \.(gif|ico|css|js|woff|woff2|ttf|svg)$ {
         root /var/www/transcendence;
    #     expires 30d;
    #     add_header Cache-Control "public";
    }
}